services:

  ac-database:
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/playerbots.cnf:ro
      
  ac-worldserver:
    restart: "no"
    environment:
      DOCKER_VOL_DATA=./client_data
    volumes:
      - ./modules:/azerothcore/modules:ro
      - ./data_client:/azerothcore/env/dist/data/:ro

  ac-worldserver-watcher:
    container_name: ac-worldserver-watcher
    build:
      context: ./watcher
    networks:
      - ac-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD:-password}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./env/dist/logs:/logs:ro
    depends_on:
      - ac-database
      - ac-authserver