/*
 * mod-loot-beam loader
 *
 * The name below is generated by the core's module loader from the module directory name
 * ("mod-loot-beam" -> "mod_loot_beam" -> "Addmod_loot_beamScripts"), so it must not be changed.
 */

void AddSC_mod_loot_beam();

void Addmod_loot_beamScripts()
{
    AddSC_mod_loot_beam();
}
